# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-01-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
            options={
                'db_table': 'tbl_employee',
            },
        ),
    ]
